import type { ProviderDefinition } from "./types";

export const providerRegistry: ProviderDefinition[] = [
  {
    id: "tavily",
    displayName: "Tavily",
    familyName: "Tavily",
    category: "AI Search",
    icon: "tavily",
    dashboardUrl: "https://app.tavily.com/home",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "brave",
    displayName: "Brave",
    familyName: "Brave",
    category: "AI Search",
    icon: "brave",
    dashboardUrl: "https://api.search.brave.com/app/dashboard",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: true,
  },
  {
    id: "serpapi",
    displayName: "SerpAPI",
    familyName: "SerpAPI",
    category: "AI Search",
    icon: "serpapi",
    dashboardUrl: "https://serpapi.com/dashboard",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "serper",
    displayName: "Serper",
    familyName: "Serper",
    category: "AI Search",
    icon: "serper",
    dashboardUrl: "https://serper.dev/api-key",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "exa",
    displayName: "Exa",
    familyName: "Exa",
    category: "AI Search",
    icon: "exa",
    dashboardUrl: "https://dashboard.exa.ai/",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "bocha",
    displayName: "Bocha",
    familyName: "Bocha",
    category: "AI Search",
    icon: "bocha",
    dashboardUrl: "https://open.bochaai.com",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "anysearch",
    displayName: "AnySearch",
    familyName: "AnySearch",
    category: "AI Search",
    icon: "anysearch",
    dashboardUrl: "https://app.anysearch.ai/login",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "wxmp",
    displayName: "WeChat Search",
    familyName: "WeChat Search",
    category: "AI Search",
    icon: "wxmp",
    dashboardUrl: "https://www.dajiala.com/main/interface?actnav=1",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "querit",
    displayName: "Querit",
    familyName: "Querit",
    category: "AI Search",
    icon: "querit",
    dashboardUrl: "https://www.querit.ai/en/dashboard/usage",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "deepseek",
    displayName: "DeepSeek",
    familyName: "DeepSeek",
    category: "LLM",
    planType: "Balance",
    icon: "deepseek",
    dashboardUrl: "https://platform.deepseek.com/usage",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "claude",
    displayName: "Claude",
    familyName: "Anthropic",
    category: "LLM",
    planType: "Pro",
    icon: "claude",
    dashboardUrl: "https://claude.ai/settings/billing",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "anthropic_credits",
    displayName: "Anthropic Credits",
    familyName: "Anthropic",
    category: "LLM",
    planType: "Credits",
    icon: "anthropic",
    dashboardUrl: "https://claude.ai/settings/billing",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "codex",
    displayName: "Codex",
    familyName: "OpenAI",
    category: "LLM",
    planType: "Pro",
    icon: "codex",
    dashboardUrl: "https://chatgpt.com",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "kimi",
    displayName: "Kimi",
    familyName: "Moonshot",
    category: "LLM",
    planType: "Membership",
    icon: "kimi",
    dashboardUrl: "https://www.kimi.com/membership/subscription?tab=quota",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "opencode_go",
    displayName: "OpenCode Go",
    familyName: "OpenCode",
    category: "LLM",
    planType: "Subscription",
    icon: "codex",
    dashboardUrl: "https://opencode.ai/docs/zh-cn/go",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "xfyun_coding_plan",
    displayName: "XFYun Spark",
    familyName: "XFYun Spark",
    category: "LLM",
    planType: "Coding Plan",
    icon: "xfyun",
    dashboardUrl: "https://maas.xfyun.cn/packageSubscription",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "volcengine_coding_plan",
    displayName: "Volcengine",
    familyName: "Volcengine",
    category: "LLM",
    planType: "Coding Plan",
    icon: "volcengine",
    dashboardUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "aliyun_coding_plan",
    displayName: "Aliyun",
    familyName: "Aliyun",
    category: "LLM",
    planType: "Coding Plan",
    icon: "aliyun",
    dashboardUrl: "https://bailian.console.aliyun.com/cn-beijing?tab=model#/efm/coding_plan",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "tencent_cloud_coding_plan",
    displayName: "Tencent Cloud",
    familyName: "Tencent Cloud",
    category: "LLM",
    planType: "Coding Plan",
    icon: "tencent",
    dashboardUrl: "https://console.cloud.tencent.com/tokenhub/codingplan",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
];
