import type { ProviderDefinition } from "./types";

export const providerRegistry: ProviderDefinition[] = [
  {
    id: "tavily",
    displayName: "Tavily",
    familyName: "Tavily",
    category: "AI Search",
    icon: "tavily",
    dashboardUrl: "https://app.tavily.com/home",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "brave",
    displayName: "Brave",
    familyName: "Brave",
    category: "AI Search",
    icon: "brave",
    dashboardUrl: "https://api.search.brave.com/app/dashboard",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: true,
  },
  {
    id: "serpapi",
    displayName: "SerpAPI",
    familyName: "SerpAPI",
    category: "AI Search",
    icon: "serpapi",
    dashboardUrl: "https://serpapi.com/dashboard",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "bocha",
    displayName: "Bocha",
    familyName: "Bocha",
    category: "AI Search",
    icon: "bocha",
    dashboardUrl: "https://open.bochaai.com",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "exa",
    displayName: "Exa",
    familyName: "Exa",
    category: "AI Search",
    icon: "exa",
    dashboardUrl: "https://dashboard.exa.ai",
    supportsReauth: false,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "claude",
    displayName: "Claude",
    familyName: "Anthropic",
    category: "LLM",
    planType: "Pro",
    icon: "claude",
    dashboardUrl: "https://claude.ai/settings/billing",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "codex",
    displayName: "Codex",
    familyName: "OpenAI",
    category: "LLM",
    planType: "Pro",
    icon: "codex",
    dashboardUrl: "https://chatgpt.com",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "kimi",
    displayName: "Kimi",
    familyName: "Moonshot",
    category: "LLM",
    planType: "Membership",
    icon: "kimi",
    dashboardUrl: "https://www.kimi.com/membership/subscription?tab=quota",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "xfyun_coding_plan",
    displayName: "XFYun Spark",
    familyName: "XFYun Spark",
    category: "LLM",
    planType: "Coding Plan",
    icon: "xfyun",
    dashboardUrl: "https://maas.xfyun.cn/packageSubscription",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "volcengine_coding_plan",
    displayName: "Volcengine",
    familyName: "Volcengine",
    category: "LLM",
    planType: "Coding Plan",
    icon: "volcengine",
    dashboardUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "aliyun_coding_plan",
    displayName: "Aliyun",
    familyName: "Aliyun",
    category: "LLM",
    planType: "Coding Plan",
    icon: "aliyun",
    dashboardUrl: "https://bailian.console.aliyun.com/cn-beijing?tab=model#/efm/coding_plan",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
  {
    id: "tencent_cloud_coding_plan",
    displayName: "Tencent Cloud",
    familyName: "Tencent Cloud",
    category: "LLM",
    planType: "Coding Plan",
    icon: "tencent",
    dashboardUrl: "https://console.cloud.tencent.com/tokenhub/codingplan",
    supportsReauth: true,
    supportsRefresh: true,
    quotaCheckConsumesSearchQuota: false,
  },
];
